### ISSUE TITLE
xbox version

### ISSUE THREAD

**Issue by boxcar32** [djp952/pvr.rtlradio#35] opened 2022-04-23 13:26 UTC
Hi,

Will there be an Xbox version? I was able to get this to work with Windows 11, ubuntu, raspberry pi 400. I tried using the windows 10 x64 and 32 on the Xbox series x but the install fails. 

Thanks,

**Comment by djp952** [comment] 2022-04-24 01:26
XBox requires a Universal Windows build and, sadly a custom Kodi package as well.  I was originally going to do this, there was some reason that it wouldn't work on Univeral Windows, but I honestly don't recall what that was.  I can revisit this and at least remember what the problem is.  I've gotten pretty good at putting square pegs into round holes on this project, perhaps something that seemed unsolvable before might become solvable!

It is important to re-mention that for UWP I would need to provide the entire Kodi .APPX file with the addon cooked in and it would need to be side-loaded. There is no way to install binary .zip addons in that environment. This disconnects you from Windows Store, so updates to Kodi become manual, and sadly, you also have to wait for me to catch up and create an updated one.  They (Kodi) don't normally publish the "final" .APPX files for each release so sometimes I have to grab the final "nightly" builds, which while the code is identical sometimes has the wrong version number.  You might see "Kodi 19.3" even it it's "Kodi 19.4", for example.  AND (can you believe there is more? LOL) .. you also have to install a trusted root certificate from me to actually install my .APPX.  Point being, you're putting quite a lot of trust in me here.

But, the good news is that the TV PVR addon I maintain does all this and has for years, and I think only once or twice did anyone have to actually ask me to repackage for a new Kodi build. Never any complaints about the custom Kodi .APPX either.

UWP/XBox is ... tedious ... to support but I promise I will unless there really was some show-stopping issue with the code.  I'm working on adding HD Radio to this addon now (along with other improvements/fixes), which is a pretty massive set of changes. Can I finish that up first before getting into XBox for you?

Oh, and I almost forgot THANK YOU for using the addon! I don't even know how people know about this thing, and the documentation is admittedly horrible, I think it's super cool that it's actually being useful and not just "academic"!

**Comment by djp952** [comment] 2022-04-24 01:28
PS - If we can do this, I might ask you to help me fix this documentation for my TV PVR project: https://github.com/djp952/pvr.hdhomerundvr/wiki/Installation-on-Kodi-Matrix-(19.x). If you scroll all the way to the bottom, you'll see an XBox logo with "TBD". I know it works on XBox but nobody has ever told me the steps!  (I don't have an XBox, clearly).

Thanks again!

**Comment by djp952** [comment] 2022-05-05 02:35
Hi @boxcar32, I did get around to re-trying this and I'm afraid that the addon requires too many third-party dependencies that simply are not compatible with Universal Windows (XBox).  The main offender back in the day was libusb, so yeah, OK maybe UWP can be rtl_tcp only like Android currently is (changing in v1.1.0!) but the addition of HD Radio and soon DAB have also brought in a number of new dependencies that were all designed for Linux and non-Microsoft tools. Getting them to work for Windows Desktop was challenging enough, UWP simply doesn't have the API surface required to pull off the same tricks.

I am very sorry, but I see no path forward for XBox, at least not one within my skill set to pull off :(

**Comment by djp952** [comment] 2022-12-24 03:30
This project will be archived; closing Issue as unresolved.

**Closed** 2022-12-24 03:31 UTC
Labels: enhancement, not-yet-possible
